/// Codex 注入侧需要展示给用户看的所有文案。
/// JS 不持有 i18n,Dart 侧在所有 /provider/* 路由返回时把当前 locale 的 labels 一并拼好。
///
/// 增删条目请同时改 zh + en,key 必须严格对齐。
const Map<String, String> shimxBridgeLabelsZh = {
  'deleteHeading': '删除对话',
  'deleteOk': '删除',
  'deleteAria': '删除对话',
  'deleteDefaultTitle': '此对话',
  'deleteSessionIdMissing': '未找到会话 id',
  'deleteFailed': '删除失败',
  'deleteSuccess': '已删除',
  'deleteConfirmPrefix': '确定删除「',
  'deleteConfirmSuffix': '」？此操作不可逆。',
  'cancel': '取消',
  'unknownError': '未知错误',
  'providerFallback': '供应商',
  'clearModel': '清除模型',
  'effortLow': '低',
  'effortMedium': '中',
  'effortHigh': '高',
  'effortXHigh': '超高',
  'healthTimeout': '超时',
  'noProviders': '还没有导入供应商',
  'unnamedProvider': '未命名供应商',
  'providerNoModels': '该供应商没有模型',
  'reasoningEffort': '思考深度',
  'saveFailed': '保存失败',
  'switchProviderFailed': '切换供应商失败',
  'switchModelFailed': '切换模型失败',
  'switchEffortFailed': '切换思考深度失败',
  'autoSwitchedToast': '已自动切换供应商',
  'autoSwitchMaintenanceToast': '自动切换已暂停',
  'autoSwitchNoEligibleToast': '当前供应商不健康,但没有符合条件的候选可切换,请手动检查',
  'probeNow': '测速',
  'threadMenu': '更多',
  'threadExport': '导出对话',
  'threadExportMarkdown': '导出为 Markdown',
  'threadExportRaw': '导出原始数据',
  'threadExportedToast': '已导出',
  'threadExportFailed': '导出失败',
  'claudeBridgeNavLabel': 'Claude 桥',
  'claudeBridgeLoading': '加载中…',
  'claudeBridgeEmpty': '未发现 Claude Code 会话',
  'claudeBridgeErrorPrefix': '加载失败:',
  'claudeBridgeBoundToast': '已绑定为接续上下文',
  'claudeBridgeUnboundToast': '已解除绑定',
  'claudeBridgeBindFailed': '绑定失败',
  'claudeBridgeNoActiveThread': '请先在 codex 中打开或选中一条对话再绑定',
  'claudeBridgeChipPrefix': 'Claude:',
  'claudeBridgeChipUnbindAria': '解除绑定',
  'claudeBridgeSessionsCount': '个会话',
  'shimxControlTitle': 'ShimX 控制',
  'shimxControlSubtitle': 'Codex 运行面板',
  'shimxControlClose': '关闭',
  'shimxControlRefresh': '刷新',
  'shimxControlRefreshAria': '刷新状态',
  'shimxControlCopy': '复制',
  'shimxControlCopyAria': '复制状态摘要',
  'shimxControlCopied': '状态已复制',
  'shimxControlCopyEmpty': '暂无可复制的状态',
  'shimxControlCopyFailed': '复制失败',
  'shimxControlLoading': '状态',
  'shimxControlChecking': '检测中…',
  'shimxControlCheckingDescription': '正在收集 Bridge、供应商、故障转移和上下文映射状态。',
  'shimxControlNoCodexThread': '未选中 Codex 对话',
  'shimxControlCurrentThread': '当前对话',
  'shimxControlThreadId': 'Thread ID',
  'shimxControlThreadWaiting': '打开已保存的 Codex 对话后，可在这里查看上下文映射。',
  'shimxControlBoundTo': '映射到',
  'shimxControlReadyToBind': '未映射',
  'shimxControlNoThreadState': '无对话',
  'shimxControlClaudeSession': 'Claude 会话',
  'shimxControlBoundVerb': '绑定',
  'shimxControlSessionSuffix': '会话',
  'shimxControlUnboundClaude': '未绑定 Claude 会话',
  'shimxControlClaudeBindingFailed': '绑定状态读取失败',
  'shimxControlClaudeBindingEmpty': '暂无 Codex 对话映射 Claude 会话',
  'shimxControlClaudeBindingCount': '个对话映射',
  'shimxControlLegacyBinding': '旧版全局绑定',
  'shimxControlBridge': 'Bridge',
  'shimxControlBridgeReady': '已连接',
  'shimxControlBridgeFailed': '不可用',
  'shimxControlBridgeDescription': '本地 RPC 通道可用，页面可以正常调用 ShimX。',
  'shimxControlBridgeErrorDescription': '注入页面暂时无法访问本地 Bridge。',
  'shimxControlProvider': '供应商',
  'shimxControlProviderEmpty': '未接管供应商',
  'shimxControlProviderFailed': '供应商不可用',
  'shimxControlProviderDescription': 'Codex 请求会通过当前供应商转发。',
  'shimxControlProviderEmptyDescription': '未覆盖供应商，Codex 使用当前默认配置。',
  'shimxControlAutoSwitch': '自动切换',
  'shimxControlAutoSwitchFailed': '自动切换不可用',
  'shimxControlAutoSwitchDescription': '供应商健康状态异常时可触发故障转移。',
  'shimxControlAutoSwitchManualDescription': '自动故障转移待命，需要时可手动切换。',
  'shimxControlClaudeBinding': '上下文映射',
  'shimxControlClaudeBindingDescription': '已映射的对话会把 Claude 上下文带入 Codex。',
  'shimxControlClaudeBindingEmptyDescription': '从侧栏选择 Claude 会话后，可在这里查看上下文映射。',
  'shimxControlBoundMetricSuffix': '条映射',
  'shimxControlCopyThreadId': '复制 ID',
  'shimxControlThreadIdCopied': 'Thread ID 已复制',
  'shimxControlStatusOk': '正常',
  'shimxControlStatusWarn': '注意',
  'shimxControlStatusError': '异常',
  'shimxControlStatusInfo': '信息',
  'shimxControlStatusIdle': '待命',
  'shimxControlStatus': '状态',
  'shimxControlStatusPreviewTab': '状态预览',
  'shimxControlRuntimeSection': '运行状态',
  'shimxControlCurrentMode': '当前模式',
  'shimxControlProviderName': '供应商名称',
  'shimxControlProviderModel': '模型',
  'shimxControlProviderModelEmpty': '透传',
  'shimxControlProviderProtocol': '协议',
  'shimxControlProviderWeights': '权重',
  'shimxControlBindingsSection': '对话映射',
  'shimxControlCodexColumn': 'Codex 对话',
  'shimxControlClaudeColumn': 'Claude 会话',
  'shimxControlOverviewTab': '数据概览',
  'shimxControlNavTitle': '面板',
  'shimxControlProviderSection': '供应商详情',
  'shimxControlLogsTab': '日志',
  'shimxControlLogsHeading': '运行日志',
  'shimxControlLogsDescription': '展示 ShimX 后端最近的日志条目,用于排查供应商/绑定问题。',
  'shimxControlLogsFilterAll': '全部',
  'shimxControlLogsFilterInfo': '信息',
  'shimxControlLogsFilterWarning': '警告',
  'shimxControlLogsFilterError': '错误',
  'shimxControlLogsEmpty': '暂无日志',
  'shimxControlLogsClear': '清空',
  'shimxControlLogsClearAria': '清空日志',
  'shimxControlLogsCleared': '已清空日志',
  'shimxControlLogsClearFailed': '清空失败',
  'shimxControlLogsCopyFailed': '复制失败',
  'shimxControlLogsReload': '重新加载',
  'shimxControlLogsLoadFailed': '加载日志失败',
  'shimxControlLogsCount': '条',
  'shimxControlBindingUnbind': '解绑',
  'shimxControlBindingUnbindAria': '解除此映射',
  'shimxControlBindingUnboundToast': '已解绑',
  'shimxControlBindingUnbindFailed': '解绑失败',
  'shimxControlActionsLabel': '操作',
  'shimxControlExportMarkdown': '导出 Markdown',
  'shimxControlExportRaw': '导出原始数据',
  'shimxControlDeleteThread': '删除对话',
  'shimxControlUnbindCurrent': '解除映射',
  'shimxControlBindingMissingThread': '当前对话尚无映射可解除',
  'shimxControlExportHtml': '导出 HTML',
  'threadExportHtml': '导出为 HTML',
  'projectMenuExportAs': '导出为',
  'projectMenuExportMarkdownZip': 'Markdown · zip',
  'projectMenuExportRawZip': '原始数据 · zip (支持导入)',
  'projectMenuImportZip': '导入 zip',
  'projectMenuImportZipAria': '把 zip 包内所有对话导入到此项目',
  'projectMenuExportHtmlZip': 'HTML · zip',
  'projectMenuExportEmpty': '该项目没有可导出的对话',
  'projectMenuExportRunning': '正在打包导出…',
  'projectMenuExportDone': '已导出',
  'projectMenuExportFailed': '导出失败',
  'projectMenuExportMissingCwd': '未识别到项目路径',
  'exportBusyMarkdown': '正在导出 Markdown…',
  'exportBusyRaws': '正在导出原始数据…',
  'exportBusyHtml': '正在导出 HTML…',
  'exportBusyBundle': '正在打包导出…',
  'shimxControlImport': '导入',
  'shimxControlImportAria': '导入会话',
  'shimxControlImportJsonl': '导入 .jsonl',
  'shimxControlImportZip': '导入 zip',
  'shimxControlImportToCurrent': '归到当前项目',
  'shimxControlImportToOriginal': '保留原始项目',
  'shimxControlImportBusyFile': '正在导入会话…',
  'shimxControlImportBusyZip': '正在导入项目…',
  'shimxControlImportDone': '导入成功',
  'shimxControlImportDoneN': '已导入',
  'shimxControlImportFailed': '导入失败',
  'shimxControlImportEmpty': '压缩包内未找到 .jsonl 文件',
  'shimxControlImportBadFile': '文件无效或为空',
  'shimxControlImportHint': '导入后 Codex 需要刷新页面才能在侧栏看到',

  'pluginMenuLabel': '插件',
  'pluginPanelTitle': '插件解锁',
  'pluginPanelClose': '关闭',
  'pluginPanelStatusLabel': '状态',
  'pluginPanelStatusIdle': '未启用',
  'pluginPanelIntroTitle': '选择数据来源',
  'pluginPanelIntroDesc': '官方 curated 插件集需要一份插件快照。选择合适的方式获取:',
  'pluginPanelActionJihulabTitle': '从极狐 GitLab 拉取(国内推荐)',
  'pluginPanelActionJihulabDesc': '走 jihulab.com 镜像,国内速度更稳,内容与 openai/plugins 保持同步',
  'pluginPanelActionGithubTitle': '从 GitHub 拉取',
  'pluginPanelActionGithubDesc': '从 openai/plugins 仓库下载最新快照(需网络可达 github.com)',
  'pluginPanelActionLocalTitle': '选择本地 zip',
  'pluginPanelActionLocalDesc': '已经手动准备好插件快照的用这个,零联网',
  'pluginPanelLocalCanceled': '未选择文件',
  'pluginPanelFooterHint': '操作会写入 codex 的 config.toml,重启 codex 后生效。',
  'pluginPanelComingSoon': '插件功能开发中',
  'pluginPanelNotReady': '插件面板未就绪',
  'pluginPanelStatusInstalled': '已安装',
  'pluginPanelStatusPartial': '已下载但未配置 config.toml',
  'pluginPanelStatusPluginCount': '插件数',
  'pluginPanelBusyDownload': '正在下载并安装…',
  'pluginPanelBusyLocal': '正在解压并安装本地 zip…',
  'pluginPanelInstallSuccess': '安装成功,重启 codex 生效',
  'pluginPanelInstallFailed': '安装失败',
  'pluginPanelStatusFailed': '读取状态失败',
  'pluginPanelLocalNotYet': '本地导入待 shimx 主界面开发中',

  'polishTooltip': '润色输入框内容',
  'polishStyleConcise': '更简洁',
  'polishStyleFormal': '更正式',
  'polishStyleCasual': '更口语',
  'polishStyleDetailed': '更详细',
  'polishEmptyInput': '请先在输入框输入文字',
  'polishNoProvider': '请先在 shimx 选一个供应商再润色',
  'polishBusy': '润色中…',
  'polishFailed': '润色失败',
  'polishPreviewTitle': '润色预览',
  'polishOriginal': '原文',
  'polishPolished': '润色后',
  'polishReplace': '替换',
  'polishCancel': '取消',
};


const Map<String, String> shimxBridgeLabelsEn = {
  'deleteHeading': 'Delete thread',
  'deleteOk': 'Delete',
  'deleteAria': 'Delete thread',
  'deleteDefaultTitle': 'this thread',
  'deleteSessionIdMissing': 'Session id not found',
  'deleteFailed': 'Delete failed',
  'deleteSuccess': 'Deleted',
  'deleteConfirmPrefix': 'Delete "',
  'deleteConfirmSuffix': '"? This cannot be undone.',
  'cancel': 'Cancel',
  'unknownError': 'Unknown error',
  'providerFallback': 'Provider',
  'clearModel': 'Clear model',
  'effortLow': 'Low',
  'effortMedium': 'Med',
  'effortHigh': 'High',
  'effortXHigh': 'XHigh',
  'healthTimeout': 'timeout',
  'noProviders': 'No providers configured yet',
  'unnamedProvider': 'Unnamed provider',
  'providerNoModels': 'No models for this provider',
  'reasoningEffort': 'Reasoning',
  'saveFailed': 'Save failed',
  'switchProviderFailed': 'Switch provider failed',
  'switchModelFailed': 'Switch model failed',
  'switchEffortFailed': 'Switch reasoning failed',
  'autoSwitchedToast': 'Provider auto-switched',
  'autoSwitchMaintenanceToast': 'Auto-switch paused',
  'autoSwitchNoEligibleToast':
      'Current provider unhealthy, but no eligible candidate to switch — please check manually',
  'probeNow': 'Measure latency',
  'threadMenu': 'More',
  'threadExport': 'Export',
  'threadExportMarkdown': 'Export as Markdown',
  'threadExportRaw': 'Export raws data',
  'threadExportedToast': 'Exported',
  'threadExportFailed': 'Export failed',
  'claudeBridgeNavLabel': 'Claude bridge',
  'claudeBridgeLoading': 'Loading…',
  'claudeBridgeEmpty': 'No Claude Code sessions found',
  'claudeBridgeErrorPrefix': 'Load failed: ',
  'claudeBridgeBoundToast': 'Bound as continuation context',
  'claudeBridgeUnboundToast': 'Unbound',
  'claudeBridgeBindFailed': 'Bind failed',
  'claudeBridgeNoActiveThread': 'Open or select a codex conversation first',
  'claudeBridgeChipPrefix': 'Claude:',
  'claudeBridgeChipUnbindAria': 'Unbind',
  'claudeBridgeSessionsCount': 'sessions',
  'shimxControlTitle': 'ShimX control',
  'shimxControlSubtitle': 'Codex runtime panel',
  'shimxControlClose': 'Close',
  'shimxControlRefresh': 'Refresh',
  'shimxControlRefreshAria': 'Refresh status',
  'shimxControlCopy': 'Copy',
  'shimxControlCopyAria': 'Copy status summary',
  'shimxControlCopied': 'Status copied',
  'shimxControlCopyEmpty': 'No status to copy yet',
  'shimxControlCopyFailed': 'Copy failed',
  'shimxControlLoading': 'Status',
  'shimxControlChecking': 'Checking…',
  'shimxControlCheckingDescription':
      'Collecting bridge, provider, failover, and context mapping status.',
  'shimxControlNoCodexThread': 'No active Codex conversation',
  'shimxControlCurrentThread': 'Current thread',
  'shimxControlThreadId': 'Thread ID',
  'shimxControlThreadWaiting':
      'Open a saved Codex conversation to inspect context mappings.',
  'shimxControlBoundTo': 'Mapped to',
  'shimxControlReadyToBind': 'Not mapped',
  'shimxControlNoThreadState': 'No thread',
  'shimxControlClaudeSession': 'Claude session',
  'shimxControlBoundVerb': 'bound to',
  'shimxControlSessionSuffix': 'session',
  'shimxControlUnboundClaude': 'has no Claude session bound',
  'shimxControlClaudeBindingFailed': 'Binding status unavailable',
  'shimxControlClaudeBindingEmpty': 'No Codex conversations are mapped',
  'shimxControlClaudeBindingCount': 'conversation mappings',
  'shimxControlLegacyBinding': 'Legacy global binding',
  'shimxControlBridge': 'Bridge',
  'shimxControlBridgeReady': 'Connected',
  'shimxControlBridgeFailed': 'Unavailable',
  'shimxControlBridgeDescription': 'Local RPC channel is reachable.',
  'shimxControlBridgeErrorDescription':
      'The injected page cannot reach the local bridge.',
  'shimxControlProvider': 'Provider',
  'shimxControlProviderEmpty': 'No active provider',
  'shimxControlProviderFailed': 'Provider unavailable',
  'shimxControlProviderDescription':
      'Requests are routed through this provider.',
  'shimxControlProviderEmptyDescription':
      'Codex is using its current default provider.',
  'shimxControlAutoSwitch': 'Auto switch',
  'shimxControlAutoSwitchFailed': 'Auto switch unavailable',
  'shimxControlAutoSwitchDescription': 'Provider health can trigger failover.',
  'shimxControlAutoSwitchManualDescription': 'Automatic failover is standing by.',
  'shimxControlClaudeBinding': 'Context mapping',
  'shimxControlClaudeBindingDescription':
      'Mapped conversations carry Claude context into Codex.',
  'shimxControlClaudeBindingEmptyDescription':
      'Select a Claude session from the sidebar to inspect context mappings here.',
  'shimxControlBoundMetricSuffix': 'mappings',
  'shimxControlCopyThreadId': 'Copy ID',
  'shimxControlThreadIdCopied': 'Thread ID copied',
  'shimxControlStatusOk': 'OK',
  'shimxControlStatusWarn': 'Warn',
  'shimxControlStatusError': 'Error',
  'shimxControlStatusInfo': 'Info',
  'shimxControlStatusIdle': 'Idle',
  'shimxControlStatus': 'Status',
  'shimxControlStatusPreviewTab': 'Status preview',
  'shimxControlRuntimeSection': 'Runtime',
  'shimxControlCurrentMode': 'Mode',
  'shimxControlProviderName': 'Provider name',
  'shimxControlProviderModel': 'Model',
  'shimxControlProviderModelEmpty': 'Passthrough',
  'shimxControlProviderProtocol': 'Protocol',
  'shimxControlProviderWeights': 'Weights',
  'shimxControlBindingsSection': 'Conversation mappings',
  'shimxControlCodexColumn': 'Codex conversation',
  'shimxControlClaudeColumn': 'Claude session',
  'shimxControlOverviewTab': 'Data overview',
  'shimxControlNavTitle': 'Sections',
  'shimxControlProviderSection': 'Provider details',
  'shimxControlLogsTab': 'Logs',
  'shimxControlLogsHeading': 'Runtime logs',
  'shimxControlLogsDescription':
      'Recent log entries from the ShimX backend, useful for diagnosing provider and binding issues.',
  'shimxControlLogsFilterAll': 'All',
  'shimxControlLogsFilterInfo': 'Info',
  'shimxControlLogsFilterWarning': 'Warn',
  'shimxControlLogsFilterError': 'Error',
  'shimxControlLogsEmpty': 'No logs yet',
  'shimxControlLogsClear': 'Clear',
  'shimxControlLogsClearAria': 'Clear logs',
  'shimxControlLogsCleared': 'Logs cleared',
  'shimxControlLogsClearFailed': 'Clear failed',
  'shimxControlLogsCopyFailed': 'Copy failed',
  'shimxControlLogsReload': 'Reload',
  'shimxControlLogsLoadFailed': 'Failed to load logs',
  'shimxControlLogsCount': 'entries',
  'shimxControlBindingUnbind': 'Unbind',
  'shimxControlBindingUnbindAria': 'Remove this mapping',
  'shimxControlBindingUnboundToast': 'Mapping removed',
  'shimxControlBindingUnbindFailed': 'Unbind failed',
  'shimxControlActionsLabel': 'Actions',
  'shimxControlExportMarkdown': 'Export as Markdown',
  'shimxControlExportRaw': 'Export raw data',
  'shimxControlDeleteThread': 'Delete thread',
  'shimxControlUnbindCurrent': 'Remove mapping',
  'shimxControlBindingMissingThread': 'No mapping to remove for this thread',
  'shimxControlExportHtml': 'Export HTML',
  'threadExportHtml': 'Export as HTML',
  'projectMenuExportAs': 'Export as',
  'projectMenuExportMarkdownZip': 'Markdown · zip',
  'projectMenuExportRawZip': 'Raw data · zip (importable)',
  'projectMenuImportZip': 'Import zip',
  'projectMenuImportZipAria':
      'Import all conversations from a zip into this project',
  'projectMenuExportHtmlZip': 'HTML · zip',
  'projectMenuExportEmpty': 'This project has no conversations to export',
  'projectMenuExportRunning': 'Packing export…',
  'projectMenuExportDone': 'Exported',
  'projectMenuExportFailed': 'Export failed',
  'projectMenuExportMissingCwd': 'Project path not detected',
  'exportBusyMarkdown': 'Exporting Markdown…',
  'exportBusyRaws': 'Exporting raw data…',
  'exportBusyHtml': 'Exporting HTML…',
  'exportBusyBundle': 'Packing export…',
  'shimxControlImport': 'Import',
  'shimxControlImportAria': 'Import conversations',
  'shimxControlImportJsonl': 'Import .jsonl',
  'shimxControlImportZip': 'Import zip',
  'shimxControlImportToCurrent': 'Assign to current project',
  'shimxControlImportToOriginal': 'Keep original project',
  'shimxControlImportBusyFile': 'Importing conversation…',
  'shimxControlImportBusyZip': 'Importing project bundle…',
  'shimxControlImportDone': 'Import succeeded',
  'shimxControlImportDoneN': 'Imported',
  'shimxControlImportFailed': 'Import failed',
  'shimxControlImportEmpty': 'No .jsonl files inside the zip',
  'shimxControlImportBadFile': 'File is invalid or empty',
  'shimxControlImportHint':
      'Reload Codex to see imported threads in the sidebar',

  'pluginMenuLabel': 'Plugins',
  'pluginPanelTitle': 'Unlock plugins',
  'pluginPanelClose': 'Close',
  'pluginPanelStatusLabel': 'Status',
  'pluginPanelStatusIdle': 'Not installed',
  'pluginPanelIntroTitle': 'Pick a data source',
  'pluginPanelIntroDesc':
      'The official curated plugin set needs a snapshot. Choose how to get it:',
  'pluginPanelActionJihulabTitle': 'Fetch from JihuLab (China mirror)',
  'pluginPanelActionJihulabDesc':
      'Uses the jihulab.com mirror, faster from mainland China. Kept in sync with openai/plugins.',
  'pluginPanelActionGithubTitle': 'Fetch from GitHub',
  'pluginPanelActionGithubDesc':
      'Download the latest snapshot from openai/plugins (needs access to github.com)',
  'pluginPanelActionLocalTitle': 'Pick a local zip',
  'pluginPanelActionLocalDesc':
      'Use this when you already have a snapshot ready — no network required',
  'pluginPanelLocalCanceled': 'No file selected',
  'pluginPanelFooterHint':
      "This writes codex's config.toml. Restart codex for changes to take effect.",
  'pluginPanelComingSoon': 'Plugin support is under development',
  'pluginPanelNotReady': 'Plugin panel not ready',
  'pluginPanelStatusInstalled': 'Installed',
  'pluginPanelStatusPartial': 'Downloaded but config.toml not written',
  'pluginPanelStatusPluginCount': 'Plugins',
  'pluginPanelBusyDownload': 'Downloading and installing…',
  'pluginPanelBusyLocal': 'Extracting and installing local zip…',
  'pluginPanelInstallSuccess': 'Installed. Restart codex to take effect.',
  'pluginPanelInstallFailed': 'Install failed',
  'pluginPanelStatusFailed': 'Failed to read status',
  'pluginPanelLocalNotYet': 'Local import comes from shimx main UI (WIP)',

  'polishTooltip': 'Polish composer text',
  'polishStyleConcise': 'More concise',
  'polishStyleFormal': 'More formal',
  'polishStyleCasual': 'More casual',
  'polishStyleDetailed': 'More detailed',
  'polishEmptyInput': 'Type something in the composer first',
  'polishNoProvider': 'Pick a shimx provider first to polish',
  'polishBusy': 'Polishing…',
  'polishFailed': 'Polish failed',
  'polishPreviewTitle': 'Polish preview',
  'polishOriginal': 'Original',
  'polishPolished': 'Polished',
  'polishReplace': 'Replace',
  'polishCancel': 'Cancel',
};

Map<String, String> shimxBridgeLabels({required bool isZh}) =>
    isZh ? shimxBridgeLabelsZh : shimxBridgeLabelsEn;
