/// Codex 注入侧需要展示给用户看的所有文案。
/// JS 不持有 i18n,Dart 侧在所有 /provider/* 路由返回时把当前 locale 的 labels 一并拼好。
///
/// 增删条目请同时改 zh + en,key 必须严格对齐。
const Map<String, String> shimBridgeLabelsZh = {
  'deleteHeading': '删除对话',
  'deleteOk': '删除',
  'deleteAria': '删除对话',
  'deleteDefaultTitle': '此对话',
  'deleteSessionIdMissing': '未找到会话 id',
  'deleteFailed': '删除失败',
  'deleteSuccess': '已删除',
  'deleteConfirmPrefix': '确定删除「',
  'deleteConfirmSuffix': '」？此操作不可逆。',
  'cancel': '取消',
  'unknownError': '未知错误',
  'providerFallback': '供应商',
  'clearModel': '清除模型',
  'effortLow': '低',
  'effortMedium': '中',
  'effortHigh': '高',
  'effortXHigh': '超高',
  'healthTimeout': '超时',
  'noProviders': '还没有导入供应商',
  'unnamedProvider': '未命名供应商',
  'providerNoModels': '该供应商没有模型',
  'reasoningEffort': '思考深度',
  'saveFailed': '保存失败',
  'switchProviderFailed': '切换供应商失败',
  'switchModelFailed': '切换模型失败',
  'switchEffortFailed': '切换思考深度失败',
  'autoSwitchedToast': '已自动切换供应商',
  'autoSwitchMaintenanceToast': '自动切换已暂停',
  'autoSwitchNoEligibleToast': '当前供应商不健康,但没有符合条件的候选可切换,请手动检查',
  'probeNow': '测速',
  'threadMenu': '更多',
  'threadExport': '导出对话',
  'threadExportMarkdown': '导出为 Markdown',
  'threadExportRaw': '导出原始数据',
  'threadExportedToast': '已导出',
  'threadExportFailed': '导出失败',
  'claudeBridgeNavLabel': 'Claude 桥',
  'claudeBridgeLoading': '加载中…',
  'claudeBridgeEmpty': '未发现 Claude Code 会话',
  'claudeBridgeErrorPrefix': '加载失败:',
  'claudeBridgeBoundToast': '已绑定为接续上下文',
  'claudeBridgeUnboundToast': '已解除绑定',
  'claudeBridgeBindFailed': '绑定失败',
  'claudeBridgeNoActiveThread': '请先在 codex 中打开或选中一条对话再绑定',
  'claudeBridgeChipPrefix': 'Claude:',
  'claudeBridgeChipUnbindAria': '解除绑定',
  'claudeBridgeSessionsCount': '个会话',
  'shimControlTitle': 'Shim 控制',
  'shimControlSubtitle': 'Codex 运行面板',
  'shimControlClose': '关闭',
  'shimControlRefresh': '刷新',
  'shimControlRefreshAria': '刷新状态',
  'shimControlCopy': '复制',
  'shimControlCopyAria': '复制状态摘要',
  'shimControlCopied': '状态已复制',
  'shimControlCopyEmpty': '暂无可复制的状态',
  'shimControlCopyFailed': '复制失败',
  'shimControlLoading': '状态',
  'shimControlChecking': '检测中…',
  'shimControlCheckingDescription': '正在收集 Bridge、供应商、故障转移和上下文映射状态。',
  'shimControlNoCodexThread': '未选中 Codex 对话',
  'shimControlCurrentThread': '当前对话',
  'shimControlThreadId': 'Thread ID',
  'shimControlThreadWaiting': '打开已保存的 Codex 对话后，可在这里查看上下文映射。',
  'shimControlBoundTo': '映射到',
  'shimControlReadyToBind': '未映射',
  'shimControlNoThreadState': '无对话',
  'shimControlClaudeSession': 'Claude 会话',
  'shimControlBoundVerb': '绑定',
  'shimControlSessionSuffix': '会话',
  'shimControlUnboundClaude': '未绑定 Claude 会话',
  'shimControlClaudeBindingFailed': '绑定状态读取失败',
  'shimControlClaudeBindingEmpty': '暂无 Codex 对话映射 Claude 会话',
  'shimControlClaudeBindingCount': '个对话映射',
  'shimControlLegacyBinding': '旧版全局绑定',
  'shimControlBridge': 'Bridge',
  'shimControlBridgeReady': '已连接',
  'shimControlBridgeFailed': '不可用',
  'shimControlBridgeDescription': '本地 RPC 通道可用，页面可以正常调用 Shim。',
  'shimControlBridgeErrorDescription': '注入页面暂时无法访问本地 Bridge。',
  'shimControlProvider': '供应商',
  'shimControlProviderEmpty': '未接管供应商',
  'shimControlProviderFailed': '供应商不可用',
  'shimControlProviderDescription': 'Codex 请求会通过当前供应商转发。',
  'shimControlProviderEmptyDescription': '未覆盖供应商，Codex 使用当前默认配置。',
  'shimControlAutoSwitch': '自动切换',
  'shimControlAutoSwitchFailed': '自动切换不可用',
  'shimControlAutoSwitchDescription': '供应商健康状态异常时可触发故障转移。',
  'shimControlAutoSwitchManualDescription': '自动故障转移待命，需要时可手动切换。',
  'shimControlClaudeBinding': '上下文映射',
  'shimControlClaudeBindingDescription': '已映射的对话会把 Claude 上下文带入 Codex。',
  'shimControlClaudeBindingEmptyDescription': '从侧栏选择 Claude 会话后，可在这里查看上下文映射。',
  'shimControlBoundMetricSuffix': '条映射',
  'shimControlCopyThreadId': '复制 ID',
  'shimControlThreadIdCopied': 'Thread ID 已复制',
  'shimControlStatusOk': '正常',
  'shimControlStatusWarn': '注意',
  'shimControlStatusError': '异常',
  'shimControlStatusInfo': '信息',
  'shimControlStatusIdle': '待命',
  'shimControlStatus': '状态',
  'shimControlStatusPreviewTab': '状态预览',
  'shimControlRuntimeSection': '运行状态',
  'shimControlCurrentMode': '当前模式',
  'shimControlProviderName': '供应商名称',
  'shimControlProviderModel': '模型',
  'shimControlProviderModelEmpty': '透传',
  'shimControlProviderProtocol': '协议',
  'shimControlProviderWeights': '权重',
  'shimControlBindingsSection': '对话映射',
  'shimControlCodexColumn': 'Codex 对话',
  'shimControlClaudeColumn': 'Claude 会话',
  'shimControlOverviewTab': '数据概览',
  'shimControlNavTitle': '面板',
  'shimControlProviderSection': '供应商详情',
  'shimControlLogsTab': '日志',
  'shimControlLogsHeading': '运行日志',
  'shimControlLogsDescription': '展示 Shim 后端最近的日志条目,用于排查供应商/绑定问题。',
  'shimControlLogsFilterAll': '全部',
  'shimControlLogsFilterInfo': '信息',
  'shimControlLogsFilterWarning': '警告',
  'shimControlLogsFilterError': '错误',
  'shimControlLogsEmpty': '暂无日志',
  'shimControlLogsClear': '清空',
  'shimControlLogsClearAria': '清空日志',
  'shimControlLogsCleared': '已清空日志',
  'shimControlLogsClearFailed': '清空失败',
  'shimControlLogsCopyFailed': '复制失败',
  'shimControlLogsReload': '重新加载',
  'shimControlLogsLoadFailed': '加载日志失败',
  'shimControlLogsCount': '条',
  'shimControlBindingUnbind': '解绑',
  'shimControlBindingUnbindAria': '解除此映射',
  'shimControlBindingUnboundToast': '已解绑',
  'shimControlBindingUnbindFailed': '解绑失败',
  'shimControlActionsLabel': '操作',
  'shimControlExportMarkdown': '导出 Markdown',
  'shimControlExportRaw': '导出原始数据',
  'shimControlDeleteThread': '删除对话',
  'shimControlUnbindCurrent': '解除映射',
  'shimControlBindingMissingThread': '当前对话尚无映射可解除',
  'shimControlExportHtml': '导出 HTML',
  'threadExportHtml': '导出为 HTML',
  'projectMenuExportAs': '导出为',
  'projectMenuExportMarkdownZip': 'Markdown · zip',
  'projectMenuExportRawZip': '原始数据 · zip (支持导入)',
  'projectMenuImportZip': '导入 zip',
  'projectMenuImportZipAria': '把 zip 包内所有对话导入到此项目',
  'projectMenuExportHtmlZip': 'HTML · zip',
  'projectMenuExportEmpty': '该项目没有可导出的对话',
  'projectMenuExportRunning': '正在打包导出…',
  'projectMenuExportDone': '已导出',
  'projectMenuExportFailed': '导出失败',
  'projectMenuExportMissingCwd': '未识别到项目路径',
  'exportBusyMarkdown': '正在导出 Markdown…',
  'exportBusyRaws': '正在导出原始数据…',
  'exportBusyHtml': '正在导出 HTML…',
  'exportBusyBundle': '正在打包导出…',
  'shimControlImport': '导入',
  'shimControlImportAria': '导入会话',
  'shimControlImportJsonl': '导入 .jsonl',
  'shimControlImportZip': '导入 zip',
  'shimControlImportToCurrent': '归到当前项目',
  'shimControlImportToOriginal': '保留原始项目',
  'shimControlImportBusyFile': '正在导入会话…',
  'shimControlImportBusyZip': '正在导入项目…',
  'shimControlImportDone': '导入成功',
  'shimControlImportDoneN': '已导入',
  'shimControlImportFailed': '导入失败',
  'shimControlImportEmpty': '压缩包内未找到 .jsonl 文件',
  'shimControlImportBadFile': '文件无效或为空',
  'shimControlImportHint': '导入后 Codex 需要刷新页面才能在侧栏看到',

  'pluginMenuLabel': '插件',
  'pluginPanelTitle': '插件解锁',
  'pluginPanelClose': '关闭',
  'pluginPanelStatusLabel': '状态',
  'pluginPanelStatusIdle': '未启用',
  'pluginPanelIntroTitle': '选择数据来源',
  'pluginPanelIntroDesc': '官方 curated 插件集需要一份插件快照。选择合适的方式获取:',
  'pluginPanelActionJihulabTitle': '从极狐 GitLab 拉取(国内推荐)',
  'pluginPanelActionJihulabDesc': '走 jihulab.com 镜像,国内速度更稳,内容与 openai/plugins 保持同步',
  'pluginPanelActionGithubTitle': '从 GitHub 拉取',
  'pluginPanelActionGithubDesc': '从 openai/plugins 仓库下载最新快照(需网络可达 github.com)',
  'pluginPanelActionLocalTitle': '选择本地 zip',
  'pluginPanelActionLocalDesc': '已经手动准备好插件快照的用这个,零联网',
  'pluginPanelLocalCanceled': '未选择文件',
  'pluginPanelFooterHint': '操作会写入 codex 的 config.toml,重启 codex 后生效。',
  'pluginPanelComingSoon': '插件功能开发中',
  'pluginPanelNotReady': '插件面板未就绪',
  'pluginPanelStatusInstalled': '已安装',
  'pluginPanelStatusPartial': '已下载但未配置 config.toml',
  'pluginPanelStatusPluginCount': '插件数',
  'pluginPanelBusyDownload': '正在下载并安装…',
  'pluginPanelBusyLocal': '正在解压并安装本地 zip…',
  'pluginPanelInstallSuccess': '安装成功,重启 codex 生效',
  'pluginPanelInstallFailed': '安装失败',
  'pluginPanelStatusFailed': '读取状态失败',
  'pluginPanelLocalNotYet': '本地导入待 shim 主界面开发中',
};


const Map<String, String> shimBridgeLabelsEn = {
  'deleteHeading': 'Delete thread',
  'deleteOk': 'Delete',
  'deleteAria': 'Delete thread',
  'deleteDefaultTitle': 'this thread',
  'deleteSessionIdMissing': 'Session id not found',
  'deleteFailed': 'Delete failed',
  'deleteSuccess': 'Deleted',
  'deleteConfirmPrefix': 'Delete "',
  'deleteConfirmSuffix': '"? This cannot be undone.',
  'cancel': 'Cancel',
  'unknownError': 'Unknown error',
  'providerFallback': 'Provider',
  'clearModel': 'Clear model',
  'effortLow': 'Low',
  'effortMedium': 'Med',
  'effortHigh': 'High',
  'effortXHigh': 'XHigh',
  'healthTimeout': 'timeout',
  'noProviders': 'No providers configured yet',
  'unnamedProvider': 'Unnamed provider',
  'providerNoModels': 'No models for this provider',
  'reasoningEffort': 'Reasoning',
  'saveFailed': 'Save failed',
  'switchProviderFailed': 'Switch provider failed',
  'switchModelFailed': 'Switch model failed',
  'switchEffortFailed': 'Switch reasoning failed',
  'autoSwitchedToast': 'Provider auto-switched',
  'autoSwitchMaintenanceToast': 'Auto-switch paused',
  'autoSwitchNoEligibleToast':
      'Current provider unhealthy, but no eligible candidate to switch — please check manually',
  'probeNow': 'Measure latency',
  'threadMenu': 'More',
  'threadExport': 'Export',
  'threadExportMarkdown': 'Export as Markdown',
  'threadExportRaw': 'Export raws data',
  'threadExportedToast': 'Exported',
  'threadExportFailed': 'Export failed',
  'claudeBridgeNavLabel': 'Claude bridge',
  'claudeBridgeLoading': 'Loading…',
  'claudeBridgeEmpty': 'No Claude Code sessions found',
  'claudeBridgeErrorPrefix': 'Load failed: ',
  'claudeBridgeBoundToast': 'Bound as continuation context',
  'claudeBridgeUnboundToast': 'Unbound',
  'claudeBridgeBindFailed': 'Bind failed',
  'claudeBridgeNoActiveThread': 'Open or select a codex conversation first',
  'claudeBridgeChipPrefix': 'Claude:',
  'claudeBridgeChipUnbindAria': 'Unbind',
  'claudeBridgeSessionsCount': 'sessions',
  'shimControlTitle': 'Shim control',
  'shimControlSubtitle': 'Codex runtime panel',
  'shimControlClose': 'Close',
  'shimControlRefresh': 'Refresh',
  'shimControlRefreshAria': 'Refresh status',
  'shimControlCopy': 'Copy',
  'shimControlCopyAria': 'Copy status summary',
  'shimControlCopied': 'Status copied',
  'shimControlCopyEmpty': 'No status to copy yet',
  'shimControlCopyFailed': 'Copy failed',
  'shimControlLoading': 'Status',
  'shimControlChecking': 'Checking…',
  'shimControlCheckingDescription':
      'Collecting bridge, provider, failover, and context mapping status.',
  'shimControlNoCodexThread': 'No active Codex conversation',
  'shimControlCurrentThread': 'Current thread',
  'shimControlThreadId': 'Thread ID',
  'shimControlThreadWaiting':
      'Open a saved Codex conversation to inspect context mappings.',
  'shimControlBoundTo': 'Mapped to',
  'shimControlReadyToBind': 'Not mapped',
  'shimControlNoThreadState': 'No thread',
  'shimControlClaudeSession': 'Claude session',
  'shimControlBoundVerb': 'bound to',
  'shimControlSessionSuffix': 'session',
  'shimControlUnboundClaude': 'has no Claude session bound',
  'shimControlClaudeBindingFailed': 'Binding status unavailable',
  'shimControlClaudeBindingEmpty': 'No Codex conversations are mapped',
  'shimControlClaudeBindingCount': 'conversation mappings',
  'shimControlLegacyBinding': 'Legacy global binding',
  'shimControlBridge': 'Bridge',
  'shimControlBridgeReady': 'Connected',
  'shimControlBridgeFailed': 'Unavailable',
  'shimControlBridgeDescription': 'Local RPC channel is reachable.',
  'shimControlBridgeErrorDescription':
      'The injected page cannot reach the local bridge.',
  'shimControlProvider': 'Provider',
  'shimControlProviderEmpty': 'No active provider',
  'shimControlProviderFailed': 'Provider unavailable',
  'shimControlProviderDescription':
      'Requests are routed through this provider.',
  'shimControlProviderEmptyDescription':
      'Codex is using its current default provider.',
  'shimControlAutoSwitch': 'Auto switch',
  'shimControlAutoSwitchFailed': 'Auto switch unavailable',
  'shimControlAutoSwitchDescription': 'Provider health can trigger failover.',
  'shimControlAutoSwitchManualDescription': 'Automatic failover is standing by.',
  'shimControlClaudeBinding': 'Context mapping',
  'shimControlClaudeBindingDescription':
      'Mapped conversations carry Claude context into Codex.',
  'shimControlClaudeBindingEmptyDescription':
      'Select a Claude session from the sidebar to inspect context mappings here.',
  'shimControlBoundMetricSuffix': 'mappings',
  'shimControlCopyThreadId': 'Copy ID',
  'shimControlThreadIdCopied': 'Thread ID copied',
  'shimControlStatusOk': 'OK',
  'shimControlStatusWarn': 'Warn',
  'shimControlStatusError': 'Error',
  'shimControlStatusInfo': 'Info',
  'shimControlStatusIdle': 'Idle',
  'shimControlStatus': 'Status',
  'shimControlStatusPreviewTab': 'Status preview',
  'shimControlRuntimeSection': 'Runtime',
  'shimControlCurrentMode': 'Mode',
  'shimControlProviderName': 'Provider name',
  'shimControlProviderModel': 'Model',
  'shimControlProviderModelEmpty': 'Passthrough',
  'shimControlProviderProtocol': 'Protocol',
  'shimControlProviderWeights': 'Weights',
  'shimControlBindingsSection': 'Conversation mappings',
  'shimControlCodexColumn': 'Codex conversation',
  'shimControlClaudeColumn': 'Claude session',
  'shimControlOverviewTab': 'Data overview',
  'shimControlNavTitle': 'Sections',
  'shimControlProviderSection': 'Provider details',
  'shimControlLogsTab': 'Logs',
  'shimControlLogsHeading': 'Runtime logs',
  'shimControlLogsDescription':
      'Recent log entries from the Shim backend, useful for diagnosing provider and binding issues.',
  'shimControlLogsFilterAll': 'All',
  'shimControlLogsFilterInfo': 'Info',
  'shimControlLogsFilterWarning': 'Warn',
  'shimControlLogsFilterError': 'Error',
  'shimControlLogsEmpty': 'No logs yet',
  'shimControlLogsClear': 'Clear',
  'shimControlLogsClearAria': 'Clear logs',
  'shimControlLogsCleared': 'Logs cleared',
  'shimControlLogsClearFailed': 'Clear failed',
  'shimControlLogsCopyFailed': 'Copy failed',
  'shimControlLogsReload': 'Reload',
  'shimControlLogsLoadFailed': 'Failed to load logs',
  'shimControlLogsCount': 'entries',
  'shimControlBindingUnbind': 'Unbind',
  'shimControlBindingUnbindAria': 'Remove this mapping',
  'shimControlBindingUnboundToast': 'Mapping removed',
  'shimControlBindingUnbindFailed': 'Unbind failed',
  'shimControlActionsLabel': 'Actions',
  'shimControlExportMarkdown': 'Export as Markdown',
  'shimControlExportRaw': 'Export raw data',
  'shimControlDeleteThread': 'Delete thread',
  'shimControlUnbindCurrent': 'Remove mapping',
  'shimControlBindingMissingThread': 'No mapping to remove for this thread',
  'shimControlExportHtml': 'Export HTML',
  'threadExportHtml': 'Export as HTML',
  'projectMenuExportAs': 'Export as',
  'projectMenuExportMarkdownZip': 'Markdown · zip',
  'projectMenuExportRawZip': 'Raw data · zip (importable)',
  'projectMenuImportZip': 'Import zip',
  'projectMenuImportZipAria':
      'Import all conversations from a zip into this project',
  'projectMenuExportHtmlZip': 'HTML · zip',
  'projectMenuExportEmpty': 'This project has no conversations to export',
  'projectMenuExportRunning': 'Packing export…',
  'projectMenuExportDone': 'Exported',
  'projectMenuExportFailed': 'Export failed',
  'projectMenuExportMissingCwd': 'Project path not detected',
  'exportBusyMarkdown': 'Exporting Markdown…',
  'exportBusyRaws': 'Exporting raw data…',
  'exportBusyHtml': 'Exporting HTML…',
  'exportBusyBundle': 'Packing export…',
  'shimControlImport': 'Import',
  'shimControlImportAria': 'Import conversations',
  'shimControlImportJsonl': 'Import .jsonl',
  'shimControlImportZip': 'Import zip',
  'shimControlImportToCurrent': 'Assign to current project',
  'shimControlImportToOriginal': 'Keep original project',
  'shimControlImportBusyFile': 'Importing conversation…',
  'shimControlImportBusyZip': 'Importing project bundle…',
  'shimControlImportDone': 'Import succeeded',
  'shimControlImportDoneN': 'Imported',
  'shimControlImportFailed': 'Import failed',
  'shimControlImportEmpty': 'No .jsonl files inside the zip',
  'shimControlImportBadFile': 'File is invalid or empty',
  'shimControlImportHint':
      'Reload Codex to see imported threads in the sidebar',

  'pluginMenuLabel': 'Plugins',
  'pluginPanelTitle': 'Unlock plugins',
  'pluginPanelClose': 'Close',
  'pluginPanelStatusLabel': 'Status',
  'pluginPanelStatusIdle': 'Not installed',
  'pluginPanelIntroTitle': 'Pick a data source',
  'pluginPanelIntroDesc':
      'The official curated plugin set needs a snapshot. Choose how to get it:',
  'pluginPanelActionJihulabTitle': 'Fetch from JihuLab (China mirror)',
  'pluginPanelActionJihulabDesc':
      'Uses the jihulab.com mirror, faster from mainland China. Kept in sync with openai/plugins.',
  'pluginPanelActionGithubTitle': 'Fetch from GitHub',
  'pluginPanelActionGithubDesc':
      'Download the latest snapshot from openai/plugins (needs access to github.com)',
  'pluginPanelActionLocalTitle': 'Pick a local zip',
  'pluginPanelActionLocalDesc':
      'Use this when you already have a snapshot ready — no network required',
  'pluginPanelLocalCanceled': 'No file selected',
  'pluginPanelFooterHint':
      "This writes codex's config.toml. Restart codex for changes to take effect.",
  'pluginPanelComingSoon': 'Plugin support is under development',
  'pluginPanelNotReady': 'Plugin panel not ready',
  'pluginPanelStatusInstalled': 'Installed',
  'pluginPanelStatusPartial': 'Downloaded but config.toml not written',
  'pluginPanelStatusPluginCount': 'Plugins',
  'pluginPanelBusyDownload': 'Downloading and installing…',
  'pluginPanelBusyLocal': 'Extracting and installing local zip…',
  'pluginPanelInstallSuccess': 'Installed. Restart codex to take effect.',
  'pluginPanelInstallFailed': 'Install failed',
  'pluginPanelStatusFailed': 'Failed to read status',
  'pluginPanelLocalNotYet': 'Local import comes from shim main UI (WIP)',
};

Map<String, String> shimBridgeLabels({required bool isZh}) =>
    isZh ? shimBridgeLabelsZh : shimBridgeLabelsEn;
